# Generated by Django 5.2.8 on 2025-12-06 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='dailylog',
            old_name='migraine_occurred',
            new_name='had_migraine',
        ),
        migrations.RenameField(
            model_name='dailylog',
            old_name='screen_time_hours',
            new_name='weather_temp_c',
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='meds_taken',
            field=models.CharField(blank=True, help_text='Medication taken, if any', max_length=200),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weather_cloudiness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weather_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weather_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weather_pressure_hpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weather_wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='caffeine_mg',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate caffeine intake in mg (coffee, energy drinks…)', null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(help_text='Day this log refers to'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='migraine_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='How many hours the migraine lasted (approx.)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='migraine_intensity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–10 if you had a migraine', null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='physical_activity_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Rough total minutes of physical activity (walking, exercise, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep for this night/day', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='stress_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Subjective stress 1–5', null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
