# Generated by Django 5.2.8 on 2025-12-29 19:00

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_dailylog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='caffeine_mg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='meds_taken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='migraine_duration_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='migraine_intensity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='physical_activity_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleep_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='stress_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_log_per_user_per_date'),
        ),
    ]
