# Generated by Django 5.2.8 on 2025-12-30 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_dailylog_caffeine_mg_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='alcohol_consumption',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='heavy_meals',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='hydration_liters',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='menstruation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='physical_activity_difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_menstruation',
            field=models.BooleanField(default=False),
        ),
    ]
