# Generated by Django 5.2.8 on 2026-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dailylog_alcohol_consumption_dailylog_heavy_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sk', 'Slovenčina')], default='sk', max_length=5),
        ),
    ]
