# Generated by Django 5.2.8 on 2026-03-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_userprofile_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[("en-us", "English"), ("sk", "Slovenčina")],
                default="sk",
                max_length=5,
            ),
        ),
    ]

