# Generated by Django 5.2.8 on 2026-03-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_alter_userprofile_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="missed_days_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="missed_days_last_incremented_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]

